config/routes.rb
Rails.application.routes.draw do
  root 'authers#index'

  resources :authers do
  resources :books
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auther.rb
class Auther < ApplicationRecord
    has_many :books,dependent: :destroy
    validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :auther
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authers_controller.rb
class AuthersController < ApplicationController

  def index
    @authers = if params[:search]
      Auther.where("name LIKE ?", "%#{params[:search]}%")
    else
      Auther.all
    end
  end

  def show
    @auther = Auther.find(params[:id])
  end
  
  def new
    @auther = Auther.new
  end

  def create
    @auther = Auther.new(auther_params)

    if @auther.save
      redirect_to @auther
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @auther = Auther.find(params[:id])
  end

  def update
    @auther = Auther.find(params[:id])

    if @auther.update(auther_params)
      redirect_to @auther
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @auther = Auther.find(params[:id])
    @auther.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def auther_params
    params.require(:auther).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def create
        @auther = Auther.find(params[:auther_id])
        @book = @auther.books.create(book_params)
        redirect_to auther_path(@auther)
      end
    
      private
        def book_params
          params.require(:book).permit(:bookname)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authers_helper.rb
module AuthersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authers/_form.html.erb
<%= form_with model: auther do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% auther.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authers/edit.html.erb
<h1>Edit Auther</h1>

<%= render "form", auther: @auther %>

app/views/authers/index.html.erb
<h1>Authers</h1>
<%= form_with(url: authers_path, method: :get, local: true) do |form| %>
  <div>
    <%= form.label :search, "Search for auther:" %>
    <%= form.text_field :search %>
  </div>

  <div>
    <%= form.submit "Search" %>
  </div>
<% end %>

<ul>
  <% @authers.each do |auther| %>
    <li>
       <%= link_to auther.name, auther %>
    </li>
  <% end %>
</ul>
<%= link_to "New Auther", new_auther_path %>

app/views/authers/new.html.erb
<h1>New Auther</h1>
<%= render "form", auther: @auther %>

app/views/authers/show.html.erb
<h1>Auther Name</h1>

<p><%= @auther.name %></p>
<ul>
  <li><%= link_to "Edit", edit_auther_path(@auther) %></li>
  <li><%= link_to "Destroy", auther_path(@auther), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Auther Books</h2>


<% @auther.books.each do |book| %>
  <p>
    <strong>Book Name:</strong>
    <%= book.bookname %>
  </p>

<% end %>

<h2>Add a book:</h2>
<%= form_with model: [ @auther, @auther.books.build ] do |form| %>
  <p>
    <%= form.label :bookname %><br>
    <%= form.text_field :bookname %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crudtask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>